language: go
matrix:
  include:
    - go: 1.7.5
    - go: 1.8
    - go: tip
  allow_failures:
    - go: tip
sudo: true
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)/...
